rc-service mariadb start 2> /dev/null
mysql -e "CREATE DATABASE ${MYSQL_DATABASE};"
mysql -u root ${MYSQL_DATABASE} < wp_backup.sql
mysql -e "CREATE USER '${MYSQL_USER}'@'${MYSQL_DATABASE}.%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'${MYSQL_DATABASE}.%' IDENTIFIED BY '${MYSQL_PASSWORD}';
ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
FLUSH PRIVILEGES;"
